#!/bin/bash

IMAGE_NAME=$1
APP_NAME="api-server"

if [ -z $IMAGE_NAME ]; then
    echo "Image Name not set"
    exit 1
fi

if [ ! -x "$(command -v docker)" ]; then
    echo "Install docker"
    sudo apt update
    sudo apt install -y docker.io
    sudo systemctl start docker.service
    sudo systemctl enable docker.service
    sudo groupadd docker
    sudo usermod -aG docker ${USER}
    newgrp docker
fi

echo "Remove old version"
docker rm $APP_NAME -f

echo "Deploy application"
docker run -d -p 443:7000 -p 80:7000 --rm --name $APP_NAME $IMAGE_NAME


