#!/bin/bash

IMAGE_NAME=$1

if [ ! -x "$(command -v docker)" ]; then
    echo "Install docker"
    sudo apt update
    sudo apt install -y docker.io
    sudo systemctl start docker.service
    sudo systemctl enable docker.service
    sudo usermod -aG docker ${USER}
    newgrp docker
fi

    echo "Deploy application"
    docker run -it -p 443:7000 --rm --name api-server $IMAGE_NAME


